### ISSUE TITLE
Not showin up in filters?

### ISSUE THREAD

**Issue by realbrockenflabel** [abelbriggs1/gimp-superxBR#1]
I'm not a gimp expert but I copied the .py script to users.......plugins folder and it doesn't show
up in Gimp?

**Comment by abelbriggs1** [comment]
Apologies for not seeing this issue.

Reinstalling this plugin myself in a different environment, it appears that Python-Fu (the backend this plugin uses) is not packaged with all versions or distributions of GIMP, which causes the plugin to not load. You can see if this is the problem by checking the `Filters` menu - if `Python-fu` doesn't exist as its own category, you're missing Python support.

I'll be updating the README to note this as well as potential fixes.
